version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - cd Nexus-T
      - echo VITE_SUPABASE_URL=${VITE_SUPABASE_URL} >> .env
      - echo VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY} >> .env
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: Nexus-T/dist
  files:
    - '**/*'